# Generated by Django 3.0.5 on 2020-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_description', models.CharField(max_length=30)),
                ('item_price', models.IntegerField()),
                ('item_discount', models.FloatField()),
                ('item_availability', models.BooleanField(default=False)),
                ('item_category', models.CharField(max_length=20)),
                ('item_image', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
