# Generated by Django 3.0.5 on 2020-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cart_item', models.ManyToManyField(to='items.Item')),
            ],
        ),
    ]
